export type Producto = {
  id: string
  nombre: string
  descripcion: string
  precio: number
  precioLista: number
  categoria: "recargas" | "paquetes" | "internet" | "planes_renta" | "vehicular" | "accesorio" | "smartphone"
  subcategoria?: string
  marca: string
  imagen: string
  imagenes: string[]
  variantes: { label: string; valor: string; precio?: number }[]
  stock: number
  specs: { label: string; valor: string }[]
  beneficios?: string[]
  redes?: string[]
  requisitos?: { tipo: string; campos: string[] }[]
  esDigital?: boolean
  destacado?: boolean
  badge?: string
}

export const categorias = [
  { id: "todos",        label: "Todo" },
  { id: "recargas",     label: "Recargas" },
  { id: "paquetes",     label: "Paquetes" },
  { id: "internet",     label: "Internet" },
  { id: "planes_renta", label: "Planes de Renta" },
  { id: "vehicular",    label: "GPS Vehicular" },
  { id: "smartphone",   label: "Smartphones" },
  { id: "accesorio",    label: "Accesorios" },
]

const REDES_LIBRE = ["whatsapp", "facebook", "instagram", "x", "snapchat", "uber"]

const REQUISITOS_PORTABILIDAD_POSPAGO = [
  "Número del cliente a portar",
  "NIP de portabilidad (marcar *#062# o enviar NIP al 051)",
  "Correo electrónico",
  "INE vigente por ambos lados y legible",
  "2 números de contacto del cliente (trabajo y casa)",
  "2 referencias personales (nombre, primer apellido y celular)",
  "Firma de contrato de servicio",
]

const REQUISITOS_MIGRACION = [
  "Número telefónico actual",
  "ICCID de la SIM actual",
  "INE por ambos lados",
  "Número de contacto",
  "Número de oficina",
  "Correo electrónico",
  "2 referencias personales (nombre, primer apellido y número de contacto)",
  "Firma de contrato de servicio",
]

const REQUISITOS_LINEA_NUEVA = [
  "Número de contacto (opcional)",
  "Correo electrónico",
  "INE vigente por ambos lados y legible",
  "2 números de contacto del cliente (trabajo y casa)",
  "2 referencias personales (nombre, primer apellido y celular)",
  "Firma de contrato de servicio",
]

const REQUISITOS_PORTABILIDAD_PREPAGO = [
  "Número a portar",
  "CURP",
  "IMEI 2 del teléfono",
  "NIP de portabilidad (marcar o enviar mensaje al 051 con la palabra NIP)",
]

export const productos: Producto[] = [

  {
    id: "telcel-libre-1",
    nombre: "Plan Telcel Libre 1",
    descripcion: "Entra a la red Telcel con llamadas, mensajes y redes sociales ilimitadas. Sin plazos forzosos.",
    precio: 249,
    precioLista: 299,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["4 GB (6 GB con promo 50%)", "Llamadas ilimitadas", "SMS ilimitados", "Redes sociales sin límite", "Cashback 5%"],
    specs: [
      { label: "Datos", valor: "4 GB (6 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas México, EUA y Canadá" },
      { label: "Redes sociales", valor: "WhatsApp, Facebook, Instagram, X, Snapchat, Uber" },
      { label: "Cashback Telcel", valor: "5% mensual" },
      { label: "Plazo forzoso", valor: "Ninguno" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "$249",
  },
  {
    id: "telcel-libre-2",
    nombre: "Plan Telcel Libre 2",
    descripcion: "Más gigas para navegar. 5 GB (7.5 GB con promo), llamadas y redes ilimitadas con cashback del 5%.",
    precio: 319,
    precioLista: 369,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["5 GB (7.5 GB con promo 50%)", "Llamadas ilimitadas", "Redes sociales sin límite", "Cashback 5%", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "5 GB (7.5 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas México, EUA y Canadá" },
      { label: "Cashback Telcel", valor: "5% mensual" },
      { label: "Claro Drive", valor: "20 GB" },
      { label: "Claro Video", valor: "Incluido" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "$319",
  },
  {
    id: "telcel-libre-3",
    nombre: "Plan Telcel Libre 3",
    descripcion: "El plan más popular. 6 GB (9 GB con promo), llamadas y redes ilimitadas con cashback del 10%.",
    precio: 399,
    precioLista: 449,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["6 GB (9 GB con promo 50%)", "Llamadas ilimitadas", "Redes sociales sin límite", "Cashback 10%", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "6 GB (9 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas México, EUA y Canadá" },
      { label: "Cashback Telcel", valor: "10% mensual" },
      { label: "Claro Drive", valor: "20 GB" },
      { label: "Claro Video", valor: "Incluido" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: true,
    badge: "Más popular",
  },
  {
    id: "telcel-libre-4",
    nombre: "Plan Telcel Libre 4",
    descripcion: "10 GB (15 GB con promo), cashback 15% y todos los beneficios ilimitados.",
    precio: 499,
    precioLista: 549,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["10 GB (15 GB con promo 50%)", "Llamadas ilimitadas", "Cashback 15%", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "10 GB (15 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas México, EUA y Canadá" },
      { label: "Cashback Telcel", valor: "15% mensual" },
      { label: "Claro Drive", valor: "20 GB" },
      { label: "Claro Video", valor: "Incluido" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: true,
    badge: "Recomendado",
  },
  {
    id: "telcel-libre-5",
    nombre: "Plan Telcel Libre 5",
    descripcion: "20 GB (30 GB con promo). Para usuarios que necesitan más datos sin plazos forzosos.",
    precio: 599,
    precioLista: 699,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["20 GB (30 GB con promo 50%)", "Llamadas ilimitadas", "Cashback 15%", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "20 GB (30 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas" },
      { label: "Cashback Telcel", valor: "15% mensual" },
      { label: "Claro Drive", valor: "20 GB" },
      { label: "Claro Video", valor: "Incluido" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "Libre 5",
  },
  {
    id: "telcel-libre-6",
    nombre: "Plan Telcel Libre 6",
    descripcion: "30 GB (45 GB con promo). Ideal para trabajo y entretenimiento sin límites.",
    precio: 699,
    precioLista: 799,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["30 GB (45 GB con promo 50%)", "Llamadas ilimitadas", "Cashback 15%", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "30 GB (45 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas" },
      { label: "Cashback Telcel", valor: "15% mensual" },
      { label: "Claro Drive", valor: "20 GB" },
      { label: "Claro Video", valor: "Incluido" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "Libre 6",
  },
  {
    id: "telcel-libre-7",
    nombre: "Plan Telcel Libre 7",
    descripcion: "40 GB (60 GB con promo). El plan ideal para usuarios exigentes.",
    precio: 799,
    precioLista: 899,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["40 GB (60 GB con promo 50%)", "Llamadas ilimitadas", "Cashback 15%", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "40 GB (60 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas" },
      { label: "Cashback Telcel", valor: "15% mensual" },
      { label: "Claro Drive", valor: "20 GB" },
      { label: "Claro Video", valor: "Incluido" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: true,
    badge: "Libre 7",
  },
  {
    id: "telcel-libre-9",
    nombre: "Plan Telcel Libre 9",
    descripcion: "45 GB (67.5 GB con promo). Para quienes necesitan lo mejor de Telcel.",
    precio: 999,
    precioLista: 1099,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["45 GB (67.5 GB con promo 50%)", "Llamadas ilimitadas", "Cashback 15%"],
    specs: [
      { label: "Datos", valor: "45 GB (67.5 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas" },
      { label: "Cashback Telcel", valor: "15% mensual" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "Libre 9",
  },
  {
    id: "telcel-libre-12",
    nombre: "Plan Telcel Libre 12",
    descripcion: "55 GB (82.5 GB con promo) y cashback del 15%. El plan completo de la línea Libre.",
    precio: 1299,
    precioLista: 1399,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["55 GB (82.5 GB con promo 50%)", "Llamadas ilimitadas", "Cashback 15%"],
    specs: [
      { label: "Datos", valor: "55 GB (82.5 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas" },
      { label: "Cashback Telcel", valor: "15% mensual" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "Libre 12",
  },
  {
    id: "telcel-libre-vip",
    nombre: "Plan Telcel Libre VIP",
    descripcion: "El plan más completo de la línea Libre. 40 GB (60 GB con promo) y cashback del 42%.",
    precio: 1499,
    precioLista: 1599,
    categoria: "recargas",
    subcategoria: "sim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    variantes: [],
    stock: 100,
    redes: REDES_LIBRE,
    beneficios: ["40 GB (60 GB con promo 50%)", "Llamadas ilimitadas", "Cashback 42%", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "40 GB (60 GB con promo)" },
      { label: "Llamadas", valor: "Ilimitadas" },
      { label: "Cashback Telcel", valor: "42% mensual" },
      { label: "Claro Drive", valor: "20 GB" },
      { label: "Claro Video", valor: "Incluido" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "VIP",
  },

  {
    id: "esim-linea-nueva",
    nombre: "eSIM Telcel — Línea Nueva",
    descripcion: "Actívate en Telcel sin SIM física. Obtén un número nuevo al instante con código QR. Disponible en Región 6, 7 y 9.",
    precio: 399,
    precioLista: 449,
    categoria: "paquetes",
    subcategoria: "esim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1562408590-e32931084e23?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1562408590-e32931084e23?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    redes: REDES_LIBRE,
    beneficios: ["Número nuevo Telcel", "Activación por QR", "Entrega en horario hábil (9:00–19:00)", "Llamadas ilimitadas", "Redes sociales sin límite"],
    specs: [
      { label: "Tipo", valor: "Línea nueva" },
      { label: "Activación", valor: "Por QR — horario L-V 9:00 a 19:00" },
      { label: "Regiones", valor: "6 (Gto, Qro, Ags, SLP), 7 (Pue, Tlax, Oax, Gro, Ver), 9 (CDMX, Mex, Hgo, Mor)" },
      { label: "Lada", valor: "Asignada por el IFT — puede variar según ciudad" },
      { label: "Compatible", valor: "iPhone XS+, Samsung S20+, Pixel 3+" },
    ],
    requisitos: [
      { tipo: "Línea nueva eSIM", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: true,
    badge: "Línea nueva",
  },
  {
    id: "esim-mismo-numero",
    nombre: "eSIM Telcel — Mismo Número",
    descripcion: "Migra tu SIM física actual a eSIM sin cambiar tu número. Más seguridad y sin tarjeta física.",
    precio: 399,
    precioLista: 449,
    categoria: "paquetes",
    subcategoria: "esim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1562408590-e32931084e23?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1562408590-e32931084e23?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    redes: REDES_LIBRE,
    beneficios: ["Conservas tu número actual", "Migración de SIM a eSIM", "Activación por QR", "Sin trámites en tienda", "Llamadas ilimitadas"],
    specs: [
      { label: "Tipo", valor: "Migración SIM → eSIM" },
      { label: "Activación", valor: "Por QR — horario L-V 9:00 a 19:00" },
      { label: "Número", valor: "Conservas el tuyo" },
      { label: "Compatible", valor: "iPhone XS+, Samsung S20+, Pixel 3+" },
    ],
    requisitos: [
      { tipo: "Migración a eSIM", campos: REQUISITOS_MIGRACION },
    ],
    destacado: true,
    badge: "Mismo número",
  },
  {
    id: "esim-portabilidad",
    nombre: "eSIM Telcel — Portabilidad",
    descripcion: "Cámbiate a Telcel desde cualquier operadora y obtén beneficios durante 12 meses. Conserva tu número.",
    precio: 100,
    precioLista: 199,
    categoria: "paquetes",
    subcategoria: "esim",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1562408590-e32931084e23?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1562408590-e32931084e23?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    redes: REDES_LIBRE,
    beneficios: ["Promo 12 meses", "$100 x 30 días", "Redes sociales ilimitadas", "Llamadas y mensajes ilimitados", "Conserva tu número"],
    specs: [
      { label: "Tipo", valor: "Portabilidad" },
      { label: "Promoción", valor: "Beneficios durante 12 meses" },
      { label: "Precio", valor: "$100 x 30 días" },
      { label: "Activación", valor: "Por QR — horario L-V 9:00 a 19:00" },
      { label: "Número", valor: "Conservas el tuyo" },
      { label: "Compatible", valor: "iPhone XS+, Samsung S20+, Pixel 3+" },
    ],
    requisitos: [
      { tipo: "Portabilidad eSIM", campos: REQUISITOS_PORTABILIDAD_PREPAGO },
    ],
    destacado: true,
    badge: "Portabilidad",
  },

  {
    id: "telcel-ultra-3",
    nombre: "Telcel Ultra 3",
    descripcion: "Plan de renta con velocidad 5G ultra. 15 GB, minutos, mensajes y WhatsApp ilimitados.",
    precio: 349,
    precioLista: 399,
    categoria: "planes_renta",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    beneficios: ["15 GB", "Minutos ilimitados", "WhatsApp ilimitado", "5G Ultra", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "15 GB" },
      { label: "Minutos", valor: "Ilimitados México, EUA y Canadá" },
      { label: "WhatsApp", valor: "Ilimitado México, EUA y Canadá" },
      { label: "Red", valor: "5G Ultra velocidad" },
      { label: "Abierto", valor: "$349/mes" },
      { label: "Controlado", valor: "$399/mes" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_POSPAGO },
      { tipo: "Migración", campos: REQUISITOS_MIGRACION },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "Ultra 3",
  },
  {
    id: "telcel-ultra-4",
    nombre: "Telcel Ultra 4",
    descripcion: "25 GB con velocidad 5G ultra. El plan de renta más equilibrado para uso diario.",
    precio: 449,
    precioLista: 499,
    categoria: "planes_renta",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    beneficios: ["25 GB", "Minutos ilimitados", "WhatsApp ilimitado", "5G Ultra", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "25 GB" },
      { label: "Minutos", valor: "Ilimitados" },
      { label: "Red", valor: "5G Ultra velocidad" },
      { label: "Abierto", valor: "$449/mes" },
      { label: "Controlado", valor: "$499/mes" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_POSPAGO },
      { tipo: "Migración", campos: REQUISITOS_MIGRACION },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: true,
    badge: "Más popular",
  },
  {
    id: "telcel-ultra-5",
    nombre: "Telcel Ultra 5",
    descripcion: "40 GB con velocidad 5G ultra. Para usuarios que necesitan más datos y lo mejor de Telcel.",
    precio: 549,
    precioLista: 599,
    categoria: "planes_renta",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    beneficios: ["40 GB", "Minutos ilimitados", "WhatsApp ilimitado", "5G Ultra", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "40 GB" },
      { label: "Minutos", valor: "Ilimitados" },
      { label: "Red", valor: "5G Ultra velocidad" },
      { label: "Abierto", valor: "$549/mes" },
      { label: "Controlado", valor: "$599/mes" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_POSPAGO },
      { tipo: "Migración", campos: REQUISITOS_MIGRACION },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: true,
    badge: "Recomendado",
  },
  {
    id: "telcel-ultra-7",
    nombre: "Telcel Ultra 7",
    descripcion: "60 GB con velocidad 5G ultra. El preferido por usuarios profesionales.",
    precio: 749,
    precioLista: 799,
    categoria: "planes_renta",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    beneficios: ["60 GB", "Minutos ilimitados", "WhatsApp ilimitado", "5G Ultra", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "60 GB" },
      { label: "Minutos", valor: "Ilimitados" },
      { label: "Red", valor: "5G Ultra velocidad" },
      { label: "Abierto", valor: "$749/mes" },
      { label: "Controlado", valor: "$799/mes" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_POSPAGO },
      { tipo: "Migración", campos: REQUISITOS_MIGRACION },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: false,
    badge: "Ultra 7",
  },
  {
    id: "telcel-ultra-9",
    nombre: "Telcel Ultra 9",
    descripcion: "100 GB con velocidad 5G ultra. Para los que no quieren límites en datos.",
    precio: 949,
    precioLista: 999,
    categoria: "planes_renta",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    beneficios: ["100 GB", "Minutos ilimitados", "WhatsApp ilimitado", "5G Ultra", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "100 GB" },
      { label: "Minutos", valor: "Ilimitados" },
      { label: "Red", valor: "5G Ultra velocidad" },
      { label: "Abierto", valor: "$949/mes" },
      { label: "Controlado", valor: "$999/mes" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_POSPAGO },
      { tipo: "Migración", campos: REQUISITOS_MIGRACION },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: true,
    badge: "Ultra 9",
  },
  {
    id: "telcel-ultra-ilimitado",
    nombre: "Telcel Ultra Ilimitado",
    descripcion: "Datos ilimitados con velocidad 5G ultra. Política de uso justo: 200 GB a máxima velocidad.",
    precio: 1349,
    precioLista: 1399,
    categoria: "planes_renta",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: true,
    beneficios: ["Datos ilimitados", "200 GB máxima velocidad", "Minutos ilimitados", "WhatsApp ilimitado", "5G Ultra", "Claro Drive 20GB", "Claro Video"],
    specs: [
      { label: "Datos", valor: "Ilimitados (200 GB uso justo)" },
      { label: "Minutos", valor: "Ilimitados" },
      { label: "Red", valor: "5G Ultra velocidad" },
      { label: "Abierto", valor: "$1,349/mes" },
      { label: "Controlado", valor: "$1,399/mes" },
    ],
    requisitos: [
      { tipo: "Portabilidad", campos: REQUISITOS_PORTABILIDAD_POSPAGO },
      { tipo: "Migración", campos: REQUISITOS_MIGRACION },
      { tipo: "Línea nueva", campos: REQUISITOS_LINEA_NUEVA },
    ],
    destacado: true,
    badge: "Ilimitado",
  },

  {
    id: "wifi-telcel-399",
    nombre: "WiFi Telcel $399",
    descripcion: "Internet en casa con GB ilimitados desde $399 al mes. Sin instalación, sin citas, sin cables.",
    precio: 399,
    precioLista: 399,
    categoria: "internet",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: false,
    beneficios: ["GB ilimitados", "Mayor velocidad Telcel", "2 dispositivos simultáneos", "Claro Video", "atresplayer", "Universal+", "Sin instalación", "Sin cables"],
    specs: [
      { label: "Datos", valor: "Ilimitados" },
      { label: "Velocidad", valor: "Mayor velocidad de la red" },
      { label: "Servicio", valor: "Fijo · Módem 4G/5G a 24 meses" },
      { label: "Uso justo", valor: "150 GB luego 5 Mbps" },
      { label: "Dispositivos", valor: "2 simultáneos" },
      { label: "Streaming", valor: "Claro Video + atresplayer + Universal+" },
    ],
    requisitos: [
      { tipo: "Contratación", campos: [
        "Correo electrónico",
        "INE vigente por ambos lados",
        "Comprobante de domicilio",
        "Firma de contrato de servicio a 24 meses",
      ]},
    ],
    destacado: true,
    badge: "Desde $399",
  },
  {
    id: "wifi-telcel-799",
    nombre: "WiFi Telcel $799",
    descripcion: "Máxima velocidad 5G con GB ilimitados. Para 5 dispositivos simultáneos.",
    precio: 799,
    precioLista: 799,
    categoria: "internet",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: false,
    beneficios: ["GB ilimitados", "Máxima velocidad 5G", "5 dispositivos simultáneos", "Claro Video", "atresplayer", "Universal+"],
    specs: [
      { label: "Datos", valor: "Ilimitados" },
      { label: "Velocidad", valor: "Máxima velocidad 5G" },
      { label: "Servicio", valor: "Fijo · Módem 5G a 24 meses" },
      { label: "Uso justo", valor: "Máxima velocidad siempre" },
      { label: "Dispositivos", valor: "5 simultáneos" },
      { label: "Streaming", valor: "Claro Video + atresplayer + Universal+" },
    ],
    requisitos: [
      { tipo: "Contratación", campos: [
        "Correo electrónico",
        "INE vigente por ambos lados",
        "Comprobante de domicilio",
        "Firma de contrato de servicio a 24 meses",
      ]},
    ],
    destacado: true,
    badge: "5G",
  },
  {
    id: "wifi-telcel-1399",
    nombre: "WiFi Telcel $1,399",
    descripcion: "Internet ilimitado con movilidad incluida sin costo. Módem 5G, 10 dispositivos simultáneos.",
    precio: 1399,
    precioLista: 1399,
    categoria: "internet",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80"],
    variantes: [],
    stock: 999,
    esDigital: false,
    beneficios: ["GB ilimitados", "Máxima velocidad 5G", "10 dispositivos simultáneos", "Movilidad sin costo", "Claro Video", "atresplayer", "Universal+"],
    specs: [
      { label: "Datos", valor: "Ilimitados" },
      { label: "Velocidad", valor: "Máxima velocidad 5G" },
      { label: "Servicio", valor: "Con movilidad · Módem 5G a 24 meses" },
      { label: "Movilidad", valor: "Sin cargo adicional" },
      { label: "Dispositivos", valor: "10 simultáneos" },
      { label: "Streaming", valor: "Claro Video + atresplayer + Universal+" },
    ],
    requisitos: [
      { tipo: "Contratación", campos: [
        "Correo electrónico",
        "INE vigente por ambos lados",
        "Comprobante de domicilio",
        "Firma de contrato de servicio a 24 meses",
      ]},
    ],
    destacado: false,
    badge: "Con movilidad",
  },

  {
    id: "secmi-auto",
    nombre: "Localizador Secmi Auto",
    descripcion: "Localiza tu vehículo en tiempo real desde tu celular. Alertas de movimiento, historial de rutas y control remoto.",
    precio: 899,
    precioLista: 1199,
    categoria: "vehicular",
    marca: "Secmi",
    imagen: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=80"],
    variantes: [
      { label: "Plan Básico 1 año", valor: "basico" },
      { label: "Plan Pro 1 año", valor: "pro" },
    ],
    stock: 50,
    specs: [
      { label: "Rastreo", valor: "Tiempo real GPS" },
      { label: "Historial", valor: "90 días de rutas" },
      { label: "Alertas", valor: "Movimiento, velocidad, zona segura" },
      { label: "App", valor: "iOS y Android" },
      { label: "Red", valor: "Telcel 4G LTE" },
    ],
    destacado: true,
    badge: "GPS",
  },
  {
    id: "flotillas",
    nombre: "Control de Flotillas",
    descripcion: "Monitoreo profesional para flotillas y tractocamiones. Estado de unidades, mantenimiento preventivo y logística.",
    precio: 0,
    precioLista: 0,
    categoria: "vehicular",
    marca: "Telcel",
    imagen: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&q=80"],
    variantes: [],
    stock: 999,
    specs: [
      { label: "Unidades", valor: "Sin límite" },
      { label: "Monitoreo", valor: "Tiempo real 24/7" },
      { label: "Mantenimiento", valor: "Alertas preventivas" },
      { label: "Reportes", valor: "Logística y combustible" },
    ],
    destacado: false,
    badge: "Empresarial",
  },

  {
    id: "iphone-15",
    nombre: "iPhone 15 128GB",
    descripcion: "Chip A16 Bionic, Dynamic Island y cámara de 48MP. Compatible con eSIM Telcel.",
    precio: 17999,
    precioLista: 19999,
    categoria: "smartphone",
    marca: "Apple",
    imagen: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80"],
    variantes: [
      { label: "Negro", valor: "negro" },
      { label: "Blanco", valor: "blanco" },
      { label: "Azul", valor: "azul" },
    ],
    stock: 5,
    specs: [
      { label: "Chip", valor: "A16 Bionic" },
      { label: "Pantalla", valor: "6.1\" Super Retina XDR" },
      { label: "Cámara", valor: "48MP + 12MP" },
      { label: "Almacenamiento", valor: "128 GB" },
      { label: "eSIM", valor: "Compatible" },
      { label: "5G", valor: "Sí" },
    ],
    destacado: false,
  },
  {
    id: "samsung-s24",
    nombre: "Samsung Galaxy S24 256GB",
    descripcion: "Galaxy AI, Snapdragon 8 Gen 3 y Dynamic AMOLED 2X. Compatible con eSIM Telcel.",
    precio: 15999,
    precioLista: 17499,
    categoria: "smartphone",
    marca: "Samsung",
    imagen: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80"],
    variantes: [
      { label: "Onyx Black", valor: "negro" },
      { label: "Marble Gray", valor: "gris" },
    ],
    stock: 8,
    specs: [
      { label: "Chip", valor: "Snapdragon 8 Gen 3" },
      { label: "Pantalla", valor: "6.2\" Dynamic AMOLED 2X" },
      { label: "Cámara", valor: "50MP + 12MP + 10MP" },
      { label: "Almacenamiento", valor: "256 GB" },
      { label: "eSIM", valor: "Compatible" },
      { label: "5G", valor: "Sí" },
    ],
    destacado: false,
  },

  {
    id: "cargador-65w",
    nombre: "Cargador 65W GaN USB-C",
    descripcion: "Carga rápida universal compatible con iPhone, Samsung y laptops.",
    precio: 449,
    precioLista: 599,
    categoria: "accesorio",
    marca: "Anker",
    imagen: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80",
    imagenes: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80"],
    variantes: [],
    stock: 50,
    specs: [
      { label: "Potencia", valor: "65W GaN III" },
      { label: "Puertos", valor: "2x USB-C + 1x USB-A" },
      { label: "Compatibilidad", valor: "Universal" },
    ],
    destacado: false,
  },
]

export const getProducto = (id: string) => productos.find((p) => p.id === id)
export const getDestacados = () => productos.filter((p) => p.destacado)
export const getPorCategoria = (cat: string) =>
  cat === "todos" ? productos : productos.filter((p) => p.categoria === cat)
export const getPorSubcategoria = (sub: string) =>
  productos.filter((p) => p.subcategoria === sub)